name: angel_security
version: 3.0.0
description: Angel infrastructure for improving security, rate limiting, and more.
homepage: https://github.com/angel-dart/security
publish_to: none
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  angel_framework:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/framework
  crypto: ^3.0.1
dev_dependencies: 
  angel_auth:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/auth
  angel_production:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/production
  angel_redis:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/redis
  angel_test:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/test
  angel_validate:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/validate
  pretty_logging:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/pretty_logging
  pedantic: ^1.11.1
  test: ^1.17.8
