name: user_agent
version: 3.0.0
description: A Dart user agent detection library.
homepage: https://github.com/thosakwe/user_agent
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: ^1.17.8
  pedantic: ^1.11.1
