name: angel_poll
version: 2.0.0
description: package:angel_client support for "realtime" interactions with Angel via long polling.
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
homepage: https://github.com/angel-dart/poll
dependencies:
  angel_client: # ^1.0.0
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/client
  async: ^2.7.0
  collection: ^1.15.0
dev_dependencies:
  angel_test: 
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/test
  test: ^1.17.8
  pedantic: ^1.11.1