name: angel_sync
version: 3.0.0
description: Easily synchronize and scale WebSockets using package:pub_sub.
homepage: https://github.com/angel-dart/sync
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel_framework: #^2.0.0-alpha
   git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/framework
  angel_websocket: #^2.0.0-alpha
   git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/websocket
  pub_sub:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/pub_sub
  stream_channel: ^2.1.0
dev_dependencies:
  angel_test: #^2.0.0-alpha
   git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/test
  test: ^1.17.8
  pedantic: ^1.11.1