name: data_loader
version: 2.0.0
description: Batch and cache database lookups. Works well with GraphQL. Ported from JS.
homepage: https://github.com/angel-dart/graphql
environment:
  sdk: '>=2.10.0 <3.0.0'
dev_dependencies:
  graphql_schema:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/graphql/graphql_schema
  pedantic: ^1.0.0
  test: ^1.15.7