name: angel_graphql
version: 2.0.0
description: The fastest + easiest way to get a GraphQL backend in Dart, using Angel.
homepage: https://github.com/angel-dart/graphql
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel_file_service:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/file_service
  angel_framework:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/framework
  angel_websocket: 
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/websocket
  angel_validate: #^2.0.0
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/validate
  graphql_parser:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/graphql/graphql_parser
  graphql_schema:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/graphql/graphql_schema
  graphql_server:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/graphql/graphql_server
  http_parser: ^4.0.0
  web_socket_channel: ^2.1.0
  collection: ^1.15.0-nullsafety.4
dev_dependencies:
  angel_serialize:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/serialize/angel_serialize
  file: ^6.1.1
  logging: ^1.0.1
  pedantic: ^1.11.0

 