name: graphql_parser
version: 2.0.0
description: Parses GraphQL queries and schemas. Also includes classes for the GraphQL AST.
homepage: https://github.com/angel-dart/graphql
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  charcode: ^1.3.1
  source_span: ^1.8.1
  string_scanner: ^1.1.0
dev_dependencies:
  matcher: ^0.12.10
  pedantic: ^1.11.0
  test: ^1.17.7
