name: angel_oauth2
version: 4.0.0
description: A class containing handlers that can be used within Angel to build a spec-compliant OAuth 2.0 server.
homepage: https://github.com/angel-dart/oauth2.git
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  angel_framework: #^2.0.0-rc.0
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/framework
  angel_http_exception: #^1.0.0
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/http_exception
  crypto: ^3.0.1
  collection: ^1.15.0-nullsafety.4
dev_dependencies: 
  angel_validate: #^2.0.0-alpha
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/validate
  angel_test: #^2.0.0-alpha
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/test
  logging: ^1.0.1
  oauth2: ^2.0.0
  pedantic: ^1.11.0
  test: ^1.17.5
  uuid: ^3.0.4
