name: graphql_server
version: 2.0.0
description: Base package for implementing GraphQL servers. You might prefer `package:angel_graphql`, the fastest way to implement GraphQL backends in Dart.
homepage: https://github.com/angel-dart/graphql
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel_serialize: #^2.0.0
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/serialize/angel_serialize
  graphql_schema:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/graphql/graphql_schema
  graphql_parser:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/graphql/graphql_parser
  collection: ^1.15.0
  meta: ^1.4.0
  recase: ^4.0.0
  stream_channel: ^2.1.0
  tuple: ^2.0.0
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.7
