name: angel_cors
version: 4.0.0
description: Angel CORS middleware. Port of expressjs/cors to the Angel framework.
homepage: https://github.com/angel-dart/cors.git
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  angel_framework:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/framework
dev_dependencies:
  angel_test:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/test
  http: ^0.13.3
  pedantic: ^1.11.0
  test: ^1.17.5
