name: angel_wings
version: 1.0.0
description: Native HTTP driver for Angel, for a nice speed boost.
homepage: https://github.com/angel-dart/wings
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel_framework:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/framework
  mock_request:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/mock_request
dev_dependencies:
  angel_static: #^2.0.0
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/static
  io: ^1.0.0
  pedantic: ^1.11.1
  pretty_logging:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/pretty_logging
