name: jael_language_server
version: 0.0.0
description: Language Server Protocol implementation for the Jael templating engine.
homepage: https://github.com/angel-dart/vscode
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  args: ^2.1.1
#  dart_language_server: ^0.1.16
  file: ^6.1.2
  io: ^1.0.0
  jael:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/jael/jael
  jael_preprocessor:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/jael/jael_preprocessor
  json_rpc_2: ^3.0.1
  logging: ^1.0.1
  path: ^1.8.0
  source_span: ^1.8.1
  string_scanner: ^1.1.0
  symbol_table:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/symbol_table
  pedantic: ^1.11.0
executables:
  jael_language_server: jael_language_server
  