name: jael_web
version: 0.0.0
description: Experimental virtual DOM/SPA engine built on Jael. Supports SSR.
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  build: ^2.0.2
  build_config: ^1.0.0
  code_builder: ^4.0.0
  jael:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/jael/jael
  jael_preprocessor:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/jael/jael_preprocessor
  source_gen: ^1.0.2
dev_dependencies:
  build_runner: ^2.0.4
  build_web_compilers: ^3.0.0
  pedantic: ^1.11.1