name: angel_orm_mysql
version: 1.0.0
description: MySQL support for Angel's ORM. Includes functionality for querying and transactions.
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel_orm:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/orm/angel_orm
  logging: ^1.0.0
  pool: ^1.0.0
  #sqljocky5: ^2.2.1
  galileo_sqljocky5: ^3.0.0
  optional: ^6.0.0-nullsafety.2
dev_dependencies:
  angel_migration: #^2.0.0
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/orm/angel_migration
  angel_orm_generator:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/orm/angel_orm_generator
  angel_orm_test:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/orm/angel_orm_test
  build_runner: ^2.0.0
  test: ^1.0.0
  pedantic: ^1.0.0
