name: graphql_schema
version: 2.0.0
description: An implementation of GraphQL's type system in Dart. Basis of graphql_server.
homepage: https://github.com/angel-dart/graphql
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  collection: ^1.15.0
  meta: ^1.4.0
  source_span: ^1.8.1
dev_dependencies:
  test: ^1.17.7
  pedantic: ^1.11.0
