name: graphql_schema
version: 2.0.0
description: An implementation of GraphQL's type system in Dart. Basis of graphql_server.
homepage: https://github.com/angel-dart/graphql
publish_to: none
environment:
  sdk: '>=2.10.0 <2.12.0'
dependencies:
  collection: ^1.0.0
  meta: ^1.0.0
  source_span: ^1.0.0
dev_dependencies:
  test: ^1.15.7