name: angel_proxy
version: 4.0.0
description: Angel middleware to forward requests to another server (i.e. pub serve).
homepage: https://github.com/angel-dart/proxy
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel_framework:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/framework
  http: ^0.13.3
  http_parser: ^4.0.0
  path: ^1.8.0
dev_dependencies:
  angel_test: #^2.0.0-alpha
     git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/test
  mock_request:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/mock_request
  logging: ^1.0.1
  pedantic: ^1.11.0
  test: ^1.17.7
  
