name: angel_shelf
version: 3.0.0
description: Shelf interop with Angel. Use this to wrap existing server code.
homepage: https://github.com/angel-dart/shelf
publish_to: none
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  angel_framework:
   git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/framework
  path: ^1.8.0
  shelf: ^1.1.4
  stream_channel: ^2.1.0
dev_dependencies: 
  angel_test:
   git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/test
  pedantic: ^1.11.0
  pretty_logging:
   git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/pretty_logging
  shelf_static: ^1.0.0
  test: ^1.17.7
